<?php $brand = $this->getBrand(); ?>

<?php if ($brand): ?>
    <?php
        $brand_url = $this->helper('ak_brands/brand')->getBrandUrl($brand);
        $brand_title = $this->escapeHtml($brand->getTitle());
    ?>
    <div class="product-brand">
            <a href="<?php echo $brand_url; ?>" title="<?php echo $brand_title; ?>">
                More <?php echo $brand->getTitle(); ?> products
            </a>

    </div>
    <style>
        /** @todo move to stylesheet **/
        .product-brand {
            clear:both;
        }
    </style>
<?php endif; ?>