<?php if ($this->showBrand()): ?>
    <div class="product-brand">
        by <a href="<?php echo $this->getBrandUrl(); ?>" title="<?php echo $this->escapeHtml($this->getBrandTitle()); ?>">
            <?php echo $this->getBrandTitle(); ?>
        </a>
    </div>
    <style>
        /** @todo move to stylesheet **/
        .product-brand {
            clear:both;
        }
    </style>
<?php endif; ?>
